### ISSUE TITLE
Website broken: https://zen-fs.github.io/

### ISSUE THREAD

**Issue by oeway** [zen-fs/zen-fs.github.io#1]
Hi the website appears to be broken with 404 error.

**Comment by james-pre** [comment]
Yes, I'm currently working on migrating to a domain. Please use zen-fs.github.io/\<repo> for now. The index is available at [zenfs.dev](<https://zenfs.dev>), but it does not work as expected.

I'm looking into how GitHub pages handled the repositories, though the documentation is somewhat limited.
